[project]
name = "cat-turret"
version = "0.1.0"
description = "Automated cat turrent deterrent"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.127.0",
    "opencv-python-headless>=4.12.0.88",
    "uvicorn>=0.40.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "mediapipe==0.10.14",
    "adafruit-blinka>=8.0.0",
    "adafruit-circuitpython-pca9685>=3.4.20",
    "lgpio>=0.2.2.0",
    "adafruit-circuitpython-motor>=3.4.18",
    "psutil>=5.9.0",
    "pylx16a>=1.1.1",
    "pillow>=12.0.0",
]

